---

- hosts: all
  gather_facts: false
  tasks:
    - shell: 'echo "Hello, World" && sleep .1'
      with_sequence: start=0 end=10
      
    - shell: 'echo "Hello again, World" && sleep .1'
      with_sequence: start=0 end=10
      
    - shell: 'echo "Hello again again, World" && sleep .1'
      with_sequence: start=0 end=10
